"""Compatibility wrapper for the migrated public Binance collector."""

from autonomous_futures.data.public_collector import (
    BASE,
    CONTEXT_INTERVAL,
    INTERVALS,
    OUT,
    PRIMARY_INTERVAL,
    START_MS,
    SYMBOLS,
    build_public_url,
    fetch_funding,
    fetch_klines,
    fully_closed_end_ms,
    main,
    public_get,
    server_time,
    snapshot_path,
    write_funding,
    write_klines,
)

__all__ = [
    "BASE",
    "CONTEXT_INTERVAL",
    "INTERVALS",
    "OUT",
    "PRIMARY_INTERVAL",
    "START_MS",
    "SYMBOLS",
    "build_public_url",
    "fetch_funding",
    "fetch_klines",
    "fully_closed_end_ms",
    "main",
    "public_get",
    "server_time",
    "snapshot_path",
    "write_funding",
    "write_klines",
]
