"""High-Expectancy Macro Liquidity Sweep Scalper Engine (Phase 310 R2).

Deploys the verified 15m Macro-Confluence Liquidity Dip Scalper across SOLUSDT and ETHUSDT:
- Macro Trend Filter: Gated on Bitcoin 1h/4h regime alignment
  (Longs allowed only when BTC EMA 50 > EMA 200).
- 15m Entry Trigger: Detect volume-backed liquidity capitulation dips:
  Price > 2.5x ATR below 20 EMA, Volume > 2.2x 20 SMA, RSI 14 < 26.
- Trade Structuring: Maker Limit Orders at sweep price (0.02% maker fee).
- Protective Brackets: Stop Loss at 1.2x ATR below entry,
  Dynamic Take Profit at 2.0x ATR above entry (1.66:1 R:R).
- Momentum Decay Stop: Auto-exit after 8 bars (120 minutes) if momentum stalls.
"""

from __future__ import annotations

import dataclasses
import logging
from decimal import Decimal
from typing import Any

logger = logging.getLogger("autonomous_futures.strategy.macro_liquidity_scalper")


@dataclasses.dataclass(frozen=True)
class Candle:
    """Standard OHLCV market candle."""

    timestamp_ms: int
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: Decimal

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Candle:
        """Constructs a Candle from a dict with string/float/int keys."""
        ts = int(data.get("open_time", data.get("timestamp_ms", data.get("timestamp", 0))))
        return cls(
            timestamp_ms=ts,
            open=Decimal(str(data["open"])),
            high=Decimal(str(data["high"])),
            low=Decimal(str(data["low"])),
            close=Decimal(str(data["close"])),
            volume=Decimal(str(data["volume"])),
        )


@dataclasses.dataclass(frozen=True)
class ScalperSignal:
    """Quantitative signal generated by MacroLiquidityDipScalper."""

    symbol: str
    timestamp_ms: int
    side: str  # "BUY"
    order_type: str  # "LIMIT"
    sweep_price: Decimal
    stop_loss: Decimal
    take_profit: Decimal
    atr: Decimal
    max_hold_bars: int = 8
    is_maker: bool = True
    reward_to_risk_ratio: Decimal = Decimal("1.6667")
    dist_atr: Decimal = Decimal("0.0")
    volume_ratio: Decimal = Decimal("0.0")
    rsi: Decimal = Decimal("0.0")


def compute_ema(series: list[Decimal], span: int) -> list[Decimal]:
    """Computes Exponential Moving Average (EMA) using alpha = 2 / (span + 1)."""
    if not series:
        return []
    alpha = Decimal("2") / Decimal(str(span + 1))
    ema_vals: list[Decimal] = [series[0]]
    for val in series[1:]:
        new_ema = (val * alpha) + (ema_vals[-1] * (Decimal("1") - alpha))
        ema_vals.append(new_ema)
    return ema_vals


def compute_atr(candles: list[Candle], period: int = 14) -> list[Decimal]:
    """Computes Average True Range (ATR) over high/low/close prices."""
    if len(candles) < 2:
        return [Decimal("0")] * len(candles)

    true_ranges: list[Decimal] = [candles[0].high - candles[0].low]
    for i in range(1, len(candles)):
        c_prev = candles[i - 1].close
        high_val = candles[i].high
        low_val = candles[i].low
        tr = max(high_val - low_val, abs(high_val - c_prev), abs(low_val - c_prev))
        true_ranges.append(tr)

    atr_vals: list[Decimal] = []
    for i in range(len(candles)):
        if i < period - 1:
            atr_vals.append(Decimal("0"))
        else:
            window = true_ranges[i - period + 1 : i + 1]
            atr = sum(window) / Decimal(str(period))
            atr_vals.append(atr)
    return atr_vals


def compute_sma(series: list[Decimal], period: int) -> list[Decimal]:
    """Computes Simple Moving Average (SMA)."""
    sma_vals: list[Decimal] = []
    for i in range(len(series)):
        if i < period - 1:
            sma_vals.append(Decimal("0"))
        else:
            window = series[i - period + 1 : i + 1]
            sma = sum(window) / Decimal(str(period))
            sma_vals.append(sma)
    return sma_vals


def compute_rsi(prices: list[Decimal], period: int = 14) -> list[Decimal]:
    """Computes Relative Strength Index (RSI)."""
    if len(prices) <= period:
        return [Decimal("50")] * len(prices)

    deltas: list[Decimal] = [Decimal("0")]
    for i in range(1, len(prices)):
        deltas.append(prices[i] - prices[i - 1])

    rsi_vals: list[Decimal] = [Decimal("50")] * period
    for i in range(period, len(prices)):
        window = deltas[i - period + 1 : i + 1]
        gains = [d for d in window if d > Decimal("0")]
        losses = [-d for d in window if d < Decimal("0")]

        avg_gain = sum(gains) / Decimal(str(period)) if gains else Decimal("0")
        avg_loss = sum(losses) / Decimal(str(period)) if losses else Decimal("0")

        if avg_loss == Decimal("0"):
            rsi = Decimal("100") if avg_gain > Decimal("0") else Decimal("50")
        else:
            rs = avg_gain / avg_loss
            rsi = Decimal("100") - (Decimal("100") / (Decimal("1") + rs))
        rsi_vals.append(rsi)
    return rsi_vals


class MacroTrendFilter:
    """Macro trend regime gate based on Bitcoin 1h and 4h EMA alignment.

    Long entries are allowed only when Bitcoin is in a verified macro bull regime:
    BTC EMA 50 > EMA 200 (and close > EMA 200).
    """

    def __init__(self, ema_fast: int = 50, ema_slow: int = 200) -> None:
        self.ema_fast = ema_fast
        self.ema_slow = ema_slow

    def evaluate(
        self,
        btc_1h_candles: list[Candle],
        btc_4h_candles: list[Candle] | None = None,
    ) -> bool:
        """Returns True iff BTC 1h (and 4h if provided) EMA 50 > EMA 200."""
        if len(btc_1h_candles) < self.ema_slow:
            # Insufficient history to determine macro trend
            return False

        closes_1h = [c.close for c in btc_1h_candles]
        ema50_1h = compute_ema(closes_1h, self.ema_fast)
        ema200_1h = compute_ema(closes_1h, self.ema_slow)

        latest_close = closes_1h[-1]
        latest_ema50 = ema50_1h[-1]
        latest_ema200 = ema200_1h[-1]

        # BTC 1h regime condition: EMA 50 > EMA 200 and close > EMA 200
        is_bull_1h = latest_ema50 > latest_ema200 and latest_close > latest_ema200

        if not is_bull_1h:
            return False

        if btc_4h_candles is not None:
            if len(btc_4h_candles) < self.ema_slow:
                # Fail closed: insufficient warmup history to verify 4h macro trend
                return False
            closes_4h = [c.close for c in btc_4h_candles]
            ema50_4h = compute_ema(closes_4h, self.ema_fast)
            ema200_4h = compute_ema(closes_4h, self.ema_slow)
            is_bull_4h = ema50_4h[-1] > ema200_4h[-1]
            if not is_bull_4h:
                return False

        return True


class MacroLiquidityDipScalper:
    """15m Macro-Confluence Liquidity Dip Scalper.

    Identifies volume-backed liquidity capitulation sweeps on SOLUSDT and ETHUSDT:
    - Distance in ATR: (Close - 20 EMA) / 14 ATR < -2.5 (price > 2.5x ATR below 20 EMA)
    - Volume Spike: Volume > 2.2x 20 SMA Volume
    - RSI 14: RSI < 26.0
    - Order Execution: Maker Limit Order at sweep price
    - Brackets: Stop Loss 1.2x ATR below, Take Profit 2.0x ATR above (1.66:1 R:R)
    - Momentum Decay Stop: 8 bars (120 minutes)
    """

    ALLOWED_SYMBOLS: tuple[str, ...] = ("SOLUSDT", "ETHUSDT")

    def __init__(
        self,
        ema_span: int = 20,
        atr_period: int = 14,
        dist_atr_threshold: Decimal = Decimal("-2.5"),
        vol_spike_multiplier: Decimal = Decimal("2.2"),
        rsi_threshold: Decimal = Decimal("26.0"),
        sl_atr_mult: Decimal = Decimal("1.2"),
        tp_atr_mult: Decimal = Decimal("2.0"),
        max_hold_bars: int = 8,
    ) -> None:
        self.ema_span = ema_span
        self.atr_period = atr_period
        self.dist_atr_threshold = dist_atr_threshold
        self.vol_spike_multiplier = vol_spike_multiplier
        self.rsi_threshold = rsi_threshold
        self.sl_atr_mult = sl_atr_mult
        self.tp_atr_mult = tp_atr_mult
        self.max_hold_bars = max_hold_bars

    def evaluate_15m_bar(
        self,
        symbol: str,
        bar: Candle,
        history: list[Candle],
        macro_trend_allowed: bool,
    ) -> ScalperSignal | None:
        """Evaluates a 15m candle close and returns a ScalperSignal if dip criteria are met."""
        if symbol.upper() not in self.ALLOWED_SYMBOLS:
            return None
        if not macro_trend_allowed:
            return None

        # Build full sequence including current bar
        candles = [*history, bar]
        min_required = max(self.ema_span, self.atr_period, 20) + 1
        if len(candles) < min_required:
            return None

        closes = [c.close for c in candles]
        volumes = [c.volume for c in candles]

        # 1. 20 EMA
        ema20_vals = compute_ema(closes, self.ema_span)
        latest_ema20 = ema20_vals[-1]

        # 2. 14 ATR
        atr_vals = compute_atr(candles, self.atr_period)
        latest_atr = atr_vals[-1]
        if latest_atr <= Decimal("0"):
            return None

        # 3. Distance in ATR: (Close - 20 EMA) / 14 ATR
        dist_atr = (bar.close - latest_ema20) / latest_atr

        # 4. Volume Spike: Volume > 2.2x 20 SMA
        vol_sma_vals = compute_sma(volumes, 20)
        latest_vol_sma = vol_sma_vals[-1]
        if latest_vol_sma <= Decimal("0"):
            return None
        vol_ratio = bar.volume / latest_vol_sma
        is_vol_spike = bar.volume > (latest_vol_sma * self.vol_spike_multiplier)

        # 5. RSI 14 < 26.0
        rsi_vals = compute_rsi(closes, 14)
        latest_rsi = rsi_vals[-1]

        # Trigger condition check
        # Price > 2.5x ATR below 20 EMA: dist_atr < -2.5
        # Volume > 2.2x 20 SMA: is_vol_spike is True
        # RSI 14 < 26.0: latest_rsi < 26.0
        if dist_atr < self.dist_atr_threshold and is_vol_spike and latest_rsi < self.rsi_threshold:
            sweep_price = bar.close
            stop_loss = sweep_price - (self.sl_atr_mult * latest_atr)
            take_profit = sweep_price + (self.tp_atr_mult * latest_atr)
            reward_risk = (self.tp_atr_mult / self.sl_atr_mult).quantize(Decimal("0.0001"))

            signal = ScalperSignal(
                symbol=symbol.upper(),
                timestamp_ms=bar.timestamp_ms,
                side="BUY",
                order_type="LIMIT",
                sweep_price=sweep_price,
                stop_loss=stop_loss,
                take_profit=take_profit,
                atr=latest_atr,
                max_hold_bars=self.max_hold_bars,
                is_maker=True,
                reward_to_risk_ratio=reward_risk,
                dist_atr=dist_atr,
                volume_ratio=vol_ratio,
                rsi=latest_rsi,
            )
            logger.info(
                "15m ScalperSignal on %s at %s: dist=%.2f, vol=%.2f, rsi=%.2f, SL=%s, TP=%s",
                symbol,
                sweep_price,
                float(dist_atr),
                float(vol_ratio),
                float(latest_rsi),
                stop_loss,
                take_profit,
            )
            return signal

        return None
