"""Paper-safe research-plane contracts."""

from .cached_evaluation import (
    CachedEvaluationRun,
    CachedEvaluationWindow,
    CachedEvaluationWindowSpec,
    CachedEvaluator,
    CachedOnlyEvaluatorAdapter,
    CachedWindowEvaluation,
)
from .causal_evaluation import CausalCachedEvaluatorAdapter, materialize_causal_context
from .creator_artifacts import (
    CandidateState,
    CreatorCandidateArtifact,
    CreatorCandidateRegistry,
    CreatorCandidateRegistryEntry,
    build_creator_candidate_artifact,
    build_creator_candidate_registry,
    find_creator_candidate,
    read_creator_candidate_artifact,
    read_creator_candidate_registry,
    write_creator_candidate_artifact,
    write_creator_candidate_registry,
)
from .feature_signals import CausalFeatureSignalEvaluator, materialize_causal_features
from .learner_artifacts import (
    LearnerArtifact,
    LearnerArtifactState,
    build_learner_artifact,
    read_learner_artifact,
    verify_learner_artifact_binding,
    write_learner_artifact,
)
from .learner_evaluation import (
    CachedOnlyLearnerEvaluatorAdapter,
    LearnerEvaluationRun,
    LearnerEvaluationWindow,
    LearnerEvaluationWindowSpec,
    LearnerEvaluator,
    LearnerWindowEvaluation,
)
from .learner_inputs import LearnerInputMaterializer, LearnerInputWindow, LearnerInputWindowSpec
from .learner_runs import (
    LearnerRun,
    LearnerRunState,
    learner_run_content_hash,
    prepare_learner_run,
    read_learner_run,
    write_learner_run,
)
from .learner_training import LearnerTrainer, LearnerTrainingOutput, execute_learner_training
from .learner_training_evidence import (
    LearnerTrainingEvidence,
    LearnerTrainingEvidenceState,
    build_learner_training_evidence,
    learner_training_evidence_content_hash,
    read_learner_training_evidence,
    write_learner_training_evidence,
)
from .learner_training_pipeline import execute_learner_training_with_evidence
from .performance_metrics import TradePerformanceMetrics, calculate_performance_metrics
from .persisted_qualification import (
    PersistedQualificationBatchFailure,
    PersistedQualificationBatchResult,
    qualify_persisted_candidate,
    run_persisted_qualification_batch,
)
from .qualification_artifacts import (
    CreatorCandidateQualificationArtifact,
    QualificationComparator,
    QualificationDecision,
    QualificationGateResult,
    QualificationMetric,
    QualificationSource,
    WalkForwardQualificationPolicy,
    build_creator_candidate_qualification_artifact,
    build_walk_forward_qualification_artifact,
    read_creator_candidate_qualification_artifact,
    write_creator_candidate_qualification_artifact,
)
from .trade_simulation import (
    EquityPoint,
    SimulatedTrade,
    TradeSimulationConfig,
    TradeSimulationResult,
    simulate_cached_signals,
)
from .walk_forward import (
    PersistedWalkForwardAggregation,
    WalkForwardAggregation,
    WalkForwardSymbolSummary,
    WalkForwardWindowMetrics,
    aggregate_walk_forward_metrics,
    build_persisted_walk_forward_aggregation,
    read_walk_forward_aggregation,
    walk_forward_aggregation_hash,
    write_walk_forward_aggregation,
)

__all__ = [
    "CandidateState",
    "CreatorCandidateArtifact",
    "CreatorCandidateRegistry",
    "CreatorCandidateRegistryEntry",
    "build_creator_candidate_artifact",
    "build_creator_candidate_registry",
    "find_creator_candidate",
    "read_creator_candidate_artifact",
    "read_creator_candidate_registry",
    "write_creator_candidate_artifact",
    "write_creator_candidate_registry",
    "CachedEvaluationRun",
    "CachedEvaluationWindow",
    "CachedEvaluationWindowSpec",
    "CachedEvaluator",
    "CachedOnlyEvaluatorAdapter",
    "CachedWindowEvaluation",
    "CausalCachedEvaluatorAdapter",
    "materialize_causal_context",
    "CausalFeatureSignalEvaluator",
    "materialize_causal_features",
    "LearnerArtifact",
    "LearnerArtifactState",
    "build_learner_artifact",
    "read_learner_artifact",
    "verify_learner_artifact_binding",
    "write_learner_artifact",
    "CachedOnlyLearnerEvaluatorAdapter",
    "LearnerEvaluationRun",
    "LearnerEvaluationWindow",
    "LearnerEvaluationWindowSpec",
    "LearnerEvaluator",
    "LearnerWindowEvaluation",
    "LearnerInputMaterializer",
    "LearnerInputWindow",
    "LearnerInputWindowSpec",
    "LearnerRun",
    "LearnerRunState",
    "learner_run_content_hash",
    "prepare_learner_run",
    "read_learner_run",
    "write_learner_run",
    "LearnerTrainer",
    "LearnerTrainingOutput",
    "execute_learner_training",
    "LearnerTrainingEvidence",
    "LearnerTrainingEvidenceState",
    "build_learner_training_evidence",
    "learner_training_evidence_content_hash",
    "read_learner_training_evidence",
    "write_learner_training_evidence",
    "execute_learner_training_with_evidence",
    "TradePerformanceMetrics",
    "calculate_performance_metrics",
    "qualify_persisted_candidate",
    "PersistedQualificationBatchFailure",
    "PersistedQualificationBatchResult",
    "run_persisted_qualification_batch",
    "PersistedWalkForwardAggregation",
    "WalkForwardAggregation",
    "WalkForwardSymbolSummary",
    "WalkForwardWindowMetrics",
    "aggregate_walk_forward_metrics",
    "build_persisted_walk_forward_aggregation",
    "read_walk_forward_aggregation",
    "walk_forward_aggregation_hash",
    "write_walk_forward_aggregation",
    "EquityPoint",
    "SimulatedTrade",
    "TradeSimulationConfig",
    "TradeSimulationResult",
    "simulate_cached_signals",
    "CreatorCandidateQualificationArtifact",
    "QualificationComparator",
    "QualificationDecision",
    "QualificationGateResult",
    "QualificationMetric",
    "QualificationSource",
    "WalkForwardQualificationPolicy",
    "build_creator_candidate_qualification_artifact",
    "build_walk_forward_qualification_artifact",
    "read_creator_candidate_qualification_artifact",
    "write_creator_candidate_qualification_artifact",
]
