export type DashboardPage =
  | 'overview'
  | 'creator'
  | 'learner'
  | 'microstructure'
  | 'risk'
  | 'accounting'
  | 'market'
  | 'execution'
  | 'strategy-activation'
  | 'lifecycle'
  | 'stress'
  | 'mining'
  | 'portfolio'
  | 'testnet'
  | 'brackets'

export function pageFromHash(hash: string): DashboardPage {
  const normalized = hash.replace(/^#\/?/, '')
  if (normalized === 'creator') return 'creator'
  if (normalized === 'learner') return 'learner'
  if (normalized === 'microstructure') return 'microstructure'
  if (normalized === 'risk') return 'risk'
  if (normalized === 'accounting') return 'accounting'
  if (normalized === 'market' || normalized === 'live-market') return 'market'
  if (normalized === 'execution' || normalized === 'paper-execution') return 'execution'
  if (normalized === 'strategy-activation' || normalized === 'activation') return 'strategy-activation'
  if (normalized === 'lifecycle' || normalized === 'mission-control') return 'lifecycle'
  if (normalized === 'stress' || normalized === 'stress-resilience' || normalized === 'resilience') return 'stress'
  if (normalized === 'mining' || normalized === 'strategy-mining') return 'mining'
  if (normalized === 'portfolio' || normalized === 'portfolio-rebalancing' || normalized === 'rebalancing') return 'portfolio'
  if (normalized === 'testnet' || normalized === 'testnet-gateway' || normalized === 'gateway') return 'testnet'
  if (normalized === 'brackets' || normalized === 'bracket-positions' || normalized === 'positions') return 'brackets'
  return 'overview'
}
